name: "Build Docker Image"
description: "Loads and builds docker image."
inputs:
  docker_tag:
    description: 'Tag of Docker image'
    required: true
  docker_folder_path:
    description: 'Path to docker folder'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Build Docker image"
      shell: bash
      run: |
        docker build -t ${{ inputs.docker_tag }} ${{ inputs.docker_folder_path }}

