name: "Build Docker Image"
description: "Loads and builds docker image."
inputs:
  docker_tag:
    description: 'Tag of Docker image'
    required: true
  docker_folder_path:
    description: 'Path to docker folder'
    required: true

runs:
  using: "composite"
  steps:
    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v2

    - name: "Build Docker image"
      shell: bash
      run: |
        docker buildx create --use --driver=docker-container
        docker buildx build -t ${{ inputs.docker_tag }} \
        --cache-to="type=gha,mode=max" --cache-from="type=gha" \
        ${{ inputs.docker_folder_path }} --load
