sudo: required
services:
  - docker

before_install:
  - docker pull fmonteiroctw/mococrw_build_env
  - docker images

script:
  - mkdir build
  - docker run --rm -t -v "$(readlink -f .):/src" -v "$(readlink -f build):/build" --workdir /build fmonteiroctw/mococrw_build_env cmake -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTING=On /src
  - docker run --rm -t -v "$(readlink -f .):/src" -v "$(readlink -f build):/build" --workdir /build fmonteiroctw/mococrw_build_env make -j2
  - docker run --rm -t -v "$(readlink -f .):/src" -v "$(readlink -f build):/build" --workdir /build fmonteiroctw/mococrw_build_env ctest -j2 --output-on-failure
